version: '3.8'

services:
  mysql-db1:
    image: mysql:8.0
    container_name: mysql-dbproj
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Virmonarn123    # Match password here
      MYSQL_DATABASE: details
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  spring-app:
    build: .
    image: arnavkotak/user-service-spring-app
    container_name: my-spring-appproj
#    restart: always
    depends_on:
      - mysql-db1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db1:3306/details
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Virmonarn123
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
